<?php

namespace AppBundle\Repository;

/**
 * IngrdientValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientValueRepository extends \Doctrine\ORM\EntityRepository
{
}